version: '3'

services:
  conda:
    environment:
      ANACONDA_USER: 'nyuad-cgsb'
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - /Users/jillian/Dropbox/projects/infrastructure/nyuad-hpc-module-configs:/configs
      - ./:/pkgs/gencore_app
      - /var/run/docker.sock:/var/run/docker.sock